### ISSUE TITLE
我想问下训练的时候，文件目录包含两个子目录是怎样的两个子目录？

### ISSUE THREAD

**Issue by JasonJunjian** [boozyguo/mosaic#2]
子目录名字自定义吗？

**Comment by boozyguo** [comment]
hi, JasonJunjian

the data fold looks like:

./data/train/normal/*.jpg
./data/train/others/*.jpg
./data/val/normal/*.jpg
./data/val/others/*.jpg

**Comment by JasonJunjian** [comment]
thanks
